baseurl: "https://www.biowz.info/"
languageCode: "en-us"
title: "wang zhen"
theme: "hugo-ivy"
disqusShortname: "https-www-biowz-info"
ignoreFiles: ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 30

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"

menu:
  main:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于本站"
      url: "/cn/about/"
      weight: 2
    - name: "博客"
      url: "/cn/blog/"
      weight: 3
    - name: "简历"
      url: "/cn/resume.pdf"
      weight: 4
    - name: "标签"
      label: "tags"
      url: "/tags/"
      weight: 5
    - name: "读书"
      label: "categories"
      url: "/reading/"  # now it does not exist！
      weight: 6 
    - name: "记录"
      url: "/yang/yulu/"
      weight: 7
    - name: "English version"
      url: "/en/"
      weight: 8

      
  en:
    - name: "Home"
      url: "/en/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Blog"
      url: "/en/blog/"
      weight: 3
    - name: "Vitae"
      url: "/en/cv/"
      weight: 4
    - name: "Tags"
      label: "tags"
      url: "/tags/"
      weight: 5
    - name: "others"
      label: "categories"
      url: "/others/" #now it is not exist 
      weight: 6
    - name: "中文版"
      url: "/"
      weight: 7

params:
  description: "A little bit of data, and me"
  footer: "&copy; [wang zhen](/) | 2018 - 至今 | [My academic website](/) | [Weibo](/) "
  disqusURL: "https://www.biowz.info/"
  customJS: ["js/center-img.js", "js/right-quote.js", "js/no-highlight.js", "js/fix-footnote.js", "js/math-code.js"]
  githubContentURL: "https://github.com/horticulture-kid/biowz/tree/master/content/"
  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "https://img.etsystatic.com/il/503467/1545371137/il_570xN.1545371137_cmol.jpg?version=0"
      url: "/"
      alt: "wang zhen"
      tag: ""

  author:
    en: "wang zhen"
    cn: ""



blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false
    hrefTargetBlank: true  #这一个没有写的话会默认同一标签栏跳转到目标网页，
    #加上这个就会在新标签打开。至少现在测试在首页是这样
    #参考：https://github.com/leovan/leovan.me  文件：config.*

taxonomies:
   tag : "tags"
   category : "categories"
